import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  ArrayMinSize,
  IsArray,
  IsEnum,
  IsInt,
  IsNotEmpty,
  IsString,
  Min,
  ValidateNested,
} from 'class-validator';

export const TOURNAMENT_MATCH_TYPES = ['solo', 'squad'] as const;
export type TournamentMatchType = (typeof TOURNAMENT_MATCH_TYPES)[number];

export class CreateMatchTeamDto {
  @ApiProperty({ example: 'team_A', description: 'Stable team identifier from the tournament' })
  @IsString()
  @IsNotEmpty()
  teamId: string;

  @ApiProperty({ example: 'Alpha Squad', description: 'Display name for the team' })
  @IsString()
  @IsNotEmpty()
  teamName: string;

  @ApiProperty({
    example: ['player1', 'player2'],
    description: 'In-game usernames of all players on this team',
    type: [String],
  })
  @IsArray()
  @ArrayMinSize(1)
  @IsString({ each: true })
  players: string[];
}

export class CreateMatchDto {
  @ApiProperty({ example: 't_abc123', description: 'Tournament identifier' })
  @IsString()
  @IsNotEmpty()
  tournamentId: string;

  @ApiProperty({ example: 2, description: 'Round number within the tournament' })
  @IsInt()
  @Min(1)
  roundNumber: number;

  @ApiProperty({
    example: 'squad',
    enum: TOURNAMENT_MATCH_TYPES,
    description: 'solo or squad — determines how teams are interpreted',
  })
  @IsEnum(TOURNAMENT_MATCH_TYPES)
  matchType: TournamentMatchType;

  @ApiProperty({ type: [CreateMatchTeamDto] })
  @IsArray()
  @ArrayMinSize(2)
  @ValidateNested({ each: true })
  @Type(() => CreateMatchTeamDto)
  teams: CreateMatchTeamDto[];
}

export class MatchPlayerDto {
  @ApiProperty({ example: 'player1' })
  userName: string;

  @ApiProperty({ example: 'Player One' })
  displayName: string;

  @ApiProperty({
    example: 'https://cdn.mygame.com/avatars/player1.png',
    required: false,
    nullable: true,
  })
  avatarUrl: string | null;
}

export class MatchTeamDto {
  @ApiProperty({ example: 'team_A' })
  teamId: string;

  @ApiProperty({ example: 'Alpha Squad' })
  teamName: string;

  @ApiProperty({ type: [MatchPlayerDto] })
  players: MatchPlayerDto[];
}

export class CreateMatchDataDto {
  @ApiProperty({
    example: 'm_xyz789',
    description: 'Unique match identifier generated by the game',
  })
  matchId: string;

  @ApiProperty({ example: 'pending' })
  status: 'pending';

  @ApiProperty({ example: 'squad', enum: TOURNAMENT_MATCH_TYPES })
  matchType: TournamentMatchType;

  @ApiProperty({
    example: 'http://localhost:5173/lobby/ABC123',
    description: 'URL to access the match lobby',
  })
  matchUrl: string;

  @ApiProperty({ type: [MatchTeamDto] })
  teams: MatchTeamDto[];
}

export class CreateMatchResponseDto {
  @ApiProperty({ example: 201 })
  code: number;

  @ApiProperty({ example: true })
  success: boolean;

  @ApiProperty({ example: 'Match created successfully' })
  message: string;

  @ApiProperty({ type: CreateMatchDataDto })
  data: CreateMatchDataDto;

  @ApiProperty({ example: '2026-04-27T12:00:00.000Z' })
  timestamp: string;
}
